#!/usr/bin/env bash

## Copyright (C) 2020 ulises-jeremias, WilliamGaggiotti
## Licensed under MIT
## IMPORTANT: This script must be executed inside the docker container created for RPC
##
##     @script.name [OPTION] ARGUMENTS...
##
## Options:
##          --log-file=LOG_FILE_PATH  Logs file path, is /tmp/results.log by default.

ROOT=$(dirname "$0")

source "${ROOT}/util/opts/opts.sh" || exit 1
source "${ROOT}/util/logs.sh" || exit 1

#==========================================
# Default argument values and preprocessing
#==========================================
log_file=${log_file:-"${ROOT}/results.log"}

[ ! -f "${log_file}" ] && touch "${log_file}"

cd "${ROOT}" || exit 1

test_read() {
    src="$1"
    dest_prefix="$2"
    for i in $(seq 1 "${3}"); do
        dest="${dest_prefix}${i}.txt"

        (time ./client read --src "${src}" --dest "${dest}") &>> "${log_file}"
        echo >> "${log_file}"

        if diff "${src}" "${dest}" &> /dev/null; then
            log_success "There is no diff between ${src} and ${dest}\n\n" "read(${src}, ${dest})" "${log_file}"
        else
            log_failed "${src} is different compared to ${dest}\n\n" "read(${src}, ${dest})" "${log_file}"
        fi
    done
}

test_write() {
    src="$1"
    dest_prefix="$2"
    for i in $(seq 1 "${3}"); do
        dest="${dest_prefix}${i}.txt"

        (time ./client write --src "${src}" --dest "${dest}") &>> "${log_file}"
        echo >> "${log_file}"

        if diff "${src}" "${dest}" &> /dev/null; then
            log_success "There is no diff between ${src} and ${dest}\n\n" "write(${src}, ${dest})" "${log_file}"
        else
            log_failed "${src} is different compared to ${dest}\n\n" "write(${src}, ${dest})" "${log_file}"
        fi
    done
}

# generate binaries (execute two time due to error)
make
make

# bind rpc
rpcbind

# execute server in background
./server &

# wait until server is running
describe "Waitting for server"
sleep 1
log_success "Server running\n"

# generate files for test (small with 1024 bytes and big with 200M)
mkdir tests
fallocate -l 1024 ./tests/test_write_small.txt
fallocate -l 200M ./tests/test_write_big.txt

# execute client to write small file 10 times
test_write "./tests/test_write_small.txt" "./store/small_" 10

# execute client to write big file 10 times
test_write "./tests/test_write_big.txt" "./store/big_" 10

# execute client to read small file 10 times
test_read "./store/small_1.txt" "./tests/out/small_" 10

# execute client to read big file 10 times
test_read "./store/big_1.txt" "./tests/out/big_" 10

# clean all generated files
make clean
