#!/usr/bin/env bash

## Copyright (C) 2020 ulises-jeremias, WilliamGaggiotti
## Licensed under MIT
## IMPORTANT: This script must be executed inside the docker container created for gRPC
##
##     @script.name [OPTION] ARGUMENTS...
##
## Options:
##          --log-file=LOG_FILE_PATH  Logs file path, is /tmp/results.log by default.

ROOT=$(dirname "$0")

source "${ROOT}/util/opts/opts.sh" || exit 1
source "${ROOT}/util/logs.sh" || exit 1

#==========================================
# Default argument values and preprocessing
#==========================================
log_file=${log_file:-"${ROOT}/results.log"}

[ ! -f "${log_file}" ] && touch "${log_file}"

cd "${ROOT}" || exit 1

test_user_lookup() {
    for _ in $(seq 1 "$1"); do
        (time go run ./client/main.go) &>> "${log_file}"
        echo >> "${log_file}"
    done
}

# generate proto file
protoc --go_out=plugins=grpc:. ./user_lookup.proto

# execute server in background
go run ./server/main.go &

# wait until server is running
describe "Waitting for server"
sleep 1
log_success "Server running at port 4444\n"

# execute client with user number
test_user_lookup 10
